### PR TITLE
Bulge British

### PR DESCRIPTION
**Pull request by Edivad42**
* Create Bulge British Formations and Support Unit from the book
* Add publication Bulge: British
* Increase Flames_of_War_v4.gst version

### CODE REVIEW

**Comment by BranSUFC** [comment]
Hi edivad, are you adding Bulge British to BS?

**Comment by Edivad42** [comment]
> Hi edivad, are you adding Bulge British to BS?

Hi, yes

**Comment by BranSUFC** [comment]
> 

That’s great thank you! Is someone else working on bulge German?

**Comment by Edivad42** [comment]
> > 
> 
> That’s great thank you! Is someone else working on bulge German?

Not that I know of, you could start yourself if you're willing.

**Pull request merged**
