### PR TITLE
add basic force for armoured fist

### PR DESCRIPTION
**Pull request by AnhNhan**
- no allied support

ref #24

### CODE REVIEW

**Comment by AnhNhan** [comment]
I'm a little bit unfamiliar with BattleScribe data internals.

I have an issue remaining. I made more extensive use of Selection Entry Links to share platoons. But together with max selection constraints this seems to clash with the Selection Entry Groups. For example, the _Sherman Armoured Squadron_ allows you to have two to four _Sherman Armoured Troops_. One of the mandatory Sherman troops can be replaced, as well as one of the optional. What I did was to have an Entry Link to the Sherman troop, selectable once or twice, and two Selection Entry Groups each with an Entry Link to the Sherman troop. But selecting all four allowed Sherman troops will trigger the warning that I selected two troops too many. It seems the constraint of the Entry Link for the non-replaceable Sherman troops gets triggered by the Sherman choice groups.

image

Do you guys happen to know a way to properly set this up, or is the way around this to copy-paste the troops inside of the formations?

**Comment by hav3rchuck** [comment]
Did you add the constraint to the linked selection entry platoons?

I use the Root Selection Entries to give constraints to single platoons.  Take a look at the D-Day German file to get a better idea.
image

I found myself going back and forth between some of the army files to see the configuration vs behavior :-)

**Comment by hav3rchuck** [comment]
Also, as a note.  The file should be in `.catz` format, not `.cat`

**Comment by hav3rchuck** [comment]
> Also, as a note. The file should be in `.catz` format, not `.cat`

https://www.reddit.com/r/BattleScribe/comments/87guix/dont_know_how_to_add_catz_file_to_the_editor/ has more info

**Comment by hav3rchuck** [comment]
Ignore some of my previous stuff (I deleted it).  I am going through your file now :-)

**Comment by hav3rchuck** [comment]
image
Found your bug.  In your constraints you are marking the query as 'shared' which is at a higher level outside of the parent object.  You need to uncheck that so it is only to the Entry it is a child of.

**Comment by AnhNhan** [comment]
Oh wow, that works. Thanks for spotting it!

I'll go check everything again and tell you when I'm confident that we can do the first version. Should be this weekend.

**Comment by AnhNhan** [comment]
@hav3rchuck good news, I got around to finish this, and also add the command cards

**Comment by AnhNhan** [comment]
should close #23 too after merge!

**Comment by hav3rchuck** [comment]
Only thing I would add is you bump the version in `Flames_of_War_v4.gst` and I will download the change, make sure it works and then merge it :-)

**Comment by AnhNhan** [comment]
Bumped!

**Pull request merged**
